### ISSUE TITLE
Error creating mount Error: Request failed with status code 500

### ISSUE THREAD

**Issue by scriptcuddle** [wy580477/Rclone-Web-APP-on-Heroku#1]
i got error when i try mount https://telegra.ph/file/7991e1375c43ffb8e1c48.png
looks like you should add fuse in your repo https://forum.rclone.org/t/gui-mount-failed/18895

**Comment by wy580477** [comment]
> i got error when i try mount https://telegra.ph/file/7991e1375c43ffb8e1c48.png looks like you should add fuse in your repo https://forum.rclone.org/t/gui-mount-failed/18895

You can't do rclone mount on Heroku. 

- Heroku's linux kernel doesn't have fuse module which is needed for rclone mount.
- Even if kernel has necessary modules, you still need root access to mount the filesystem.

**Comment by scriptcuddle** [comment]
hmm so what is this repo made for? the main function of rclone is made for data migration between clouds. while what you made doesn't support that function

**Comment by wy580477** [comment]
> hmm so what is this repo made for? the main function of rclone is made for data migration between clouds. while what you made doesn't support that function

You don’t need rclone mount for that.  Just drag folder/file in Rclone WebUI explorer or run rclone copy in ttyd.

**Comment by scriptcuddle** [comment]
damn why did i just know this :/. I'm sorry for just knowing this, really thanks bro you saved my life

> > hmm so what is this repo made for? the main function of rclone is made for data migration between clouds. while what you made doesn't support that function
> 
> You don’t need rclone mount for that. Just drag folder/file in Rclone WebUI explorer or run rclone copy in ttyd.

**Comment by scriptcuddle** [comment]
and then heroku banned my account :/👍 https://telegra.ph/file/211fb1e532acb13e37a95.jpg

**Comment by wy580477** [comment]
> and then heroku banned my account :/👍 https://telegra.ph/file/211fb1e532acb13e37a95.jpg

Well, starting from yesterday it seems that Heroku are banning any repo with rclone upload traffic.

I'm going to achieve this repo and put a warning in readme.
